<?php

return [
    'CREATE TABLE IF NOT EXISTS products (id INT AUTO_INCREMENT NOT NULL, nr VARCHAR(255) NOT NULL, name VARCHAR(500) NOT NULL, product_url VARCHAR(500) NOT NULL, search_keywords VARCHAR(500) NOT NULL, description VARCHAR(500) NOT NULL, brand VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB'
];