<?php

return [
    'CREATE TABLE IF NOT EXISTS product_items (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, sku VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, retail_price DOUBLE PRECISION NOT NULL, thumbnail_url VARCHAR(500) NOT NULL, color VARCHAR(255) NOT NULL, color_family VARCHAR(255) NOT NULL, size VARCHAR(100) NOT NULL, size_family VARCHAR(255) NOT NULL, occassion VARCHAR(500) DEFAULT NULL, season VARCHAR(500) DEFAULT NULL, rating_avg DOUBLE PRECISION DEFAULT NULL, rating_acount DOUBLE PRECISION DEFAULT NULL, active SMALLINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB',
    'ALTER TABLE product_items ADD CONSTRAINT FK_298850D16E59D40D FOREIGN KEY (product_id) REFERENCES products (id)'
];
