<?php

return [
    'CREATE TABLE IF NOT EXISTS jobs (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, payload VARCHAR(500) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB'
];